name: rsjphotography
favicon: null
layout_spectrum: 0.11096884123980999
typography_spectrum: 0.6650323139037937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.010906289797276258
  lightness: 0.2656619790941477
  saturation: 0.3263151424471289
  rhythmicContrast: 0.7221628539264202
purpose: []
