name: rsjphotography
favicon: null
layout_spectrum: 0.94303
typography_spectrum: 0.47093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00020e'
    - '#c6a8b2'
    - '#516c5b'
    - '#fefefe'
    - '#dc4361'
  brandStrength: 0.1875
  lightness: 0.2656619790941477
  saturation: 0.3263151424471289
  rhythmicContrast: 0.7221628539264202
purpose: []
